"""
Run this on the VM from ~/bot_project_clean:

    python3 fix_login.py

It patches account_setup.py so /login stops requesting its own login code
(which was invalidating the code from your real login attempt) and instead
just watches for the code that arrives once YOU start the login on your
own device.
"""

path = "account_setup.py"

with open(path, "r") as f:
    content = f.read()

old = '''    wait_msg = await message.reply("Requesting a fresh login code and checking for it, please wait...")

    from telethon import TelegramClient
    from telethon.sessions import StringSession
    import engine as _engine
    import asyncio as _asyncio

    import time as _time
    request_time = _time.time()

    fresh_client = TelegramClient(StringSession(), API_ID, API_HASH)
    await fresh_client.connect()
    try:
        await fresh_client.send_code_request(phone)
    except Exception as e:
        await fresh_client.disconnect()
        await wait_msg.edit_text(f"Could not request a login code: {e}")
        return
    await fresh_client.disconnect()

    # Poll for up to ~20s, only accepting a code message that arrived AFTER this
    # specific request — this avoids ever handing back a stale/already-invalidated
    # code from an earlier attempt sitting in the same chat.
    code_text = "Could not find a fresh code message within 20 seconds — please try /login again."
    try:
        existing_client = await _engine.get_client(account["id"])
        for _attempt in range(10):'''

new = '''    wait_msg = await message.reply(
        "Now open Telegram on the device you want to log in on and enter "
        f"{phone} to start the login there. I'm watching for the code — "
        "you have up to 60 seconds..."
    )

    import engine as _engine
    import asyncio as _asyncio

    import time as _time
    request_time = _time.time()

    # We deliberately do NOT request a code ourselves here. Telegram only
    # keeps one pending login code alive per phone number at a time, and
    # requesting one from a throwaway session would invalidate the code
    # generated by the admin's own real login attempt (or vice versa),
    # causing "invalid code" errors. Instead we just watch the account's
    # existing, already-authorized session for whatever fresh code message
    # shows up once the admin starts logging in from their own device.
    code_text = "Could not find a fresh code message within 60 seconds — make sure you started the login on your device, then try /login again."
    try:
        existing_client = await _engine.get_client(account["id"])
        for _attempt in range(30):'''

if old not in content:
    print("Could not find the expected old block — file may already be patched, or differs. Aborting without changes.")
else:
    content = content.replace(old, new, 1)
    with open(path, "w") as f:
        f.write(content)
    print("Patched account_setup.py successfully.")
